# [Task1] DefaultArgs
#CUDA_VISIBLE_DEVICES=0 python train.py --dataset_name task1 --output_dim 3 --vorder_input "degree_nodecentrality,eigenvec_nodecentrality,pagerank_nodecentrality,kcore_nodecentrality" --embedder whatsnet --att_type_v OrderPE --agg_type_v PrevQ --att_type_e OrderPE --agg_type_e PrevQ --num_att_layer 2 --num_layers 1 --scorer sm --scorer_num_layers 1 --bs 1024 --lr 0.001 --sampling 40 --dropout 0.7 --optimizer "adam" --k 0 --gamma 0.99 --dim_hidden 64 --dim_edge 128 --dim_vertex 128 --epochs 100 --test_epoch 1 --evaltype test --save_epochs 1 --seed 42 --fix_seed --recalculate --use_wandb=1 --run_name='[Task1] DefaultArgs'

# [Task1] AttLayer4
#CUDA_VISIBLE_DEVICES=3 python train.py --dataset_name task1 --output_dim 3 --vorder_input "degree_nodecentrality,eigenvec_nodecentrality,pagerank_nodecentrality,kcore_nodecentrality" --embedder whatsnet --att_type_v OrderPE --agg_type_v PrevQ --att_type_e OrderPE --agg_type_e PrevQ --num_att_layer 4 --num_layers 1 --scorer sm --scorer_num_layers 1 --bs 1024 --lr 0.001 --sampling 40 --dropout 0.7 --optimizer "adam" --k 0 --gamma 0.99 --dim_hidden 64 --dim_edge 128 --dim_vertex 128 --epochs 100 --test_epoch 1 --evaltype test --save_epochs 1 --seed 42 --fix_seed --recalculate --use_wandb=1 --run_name='[Task1] AttLayer4'

# [Task1] ScorerNumLayer2
#CUDA_VISIBLE_DEVICES=0 python train.py --dataset_name task1 --output_dim 3 --vorder_input "degree_nodecentrality,eigenvec_nodecentrality,pagerank_nodecentrality,kcore_nodecentrality" --embedder whatsnet --att_type_v OrderPE --agg_type_v PrevQ --att_type_e OrderPE --agg_type_e PrevQ --num_att_layer 2 --num_layers 1 --scorer sm --scorer_num_layers 2 --bs 1024 --lr 0.001 --sampling 40 --dropout 0.7 --optimizer "adam" --k 0 --gamma 0.99 --dim_hidden 64 --dim_edge 128 --dim_vertex 128 --epochs 100 --test_epoch 1 --evaltype test --save_epochs 1 --seed 42 --fix_seed --recalculate --use_wandb=1 --run_name='[Task1] ScorerNumLayer2'

# [Task1] ScorerNumLayer4
#CUDA_VISIBLE_DEVICES=3 python train.py --dataset_name task1 --output_dim 3 --vorder_input "degree_nodecentrality,eigenvec_nodecentrality,pagerank_nodecentrality,kcore_nodecentrality" --embedder whatsnet --att_type_v OrderPE --agg_type_v PrevQ --att_type_e OrderPE --agg_type_e PrevQ --num_att_layer 2 --num_layers 1 --scorer sm --scorer_num_layers 4 --bs 1024 --lr 0.001 --sampling 40 --dropout 0.7 --optimizer "adam" --k 0 --gamma 0.99 --dim_hidden 64 --dim_edge 128 --dim_vertex 128 --epochs 100 --test_epoch 1 --evaltype test --save_epochs 1 --seed 42 --fix_seed --recalculate --use_wandb=1 --run_name='[Task1] ScorerNumLayer4'

# [Task2] DefaultArgs
CUDA_VISIBLE_DEVICES=2 python train.py --dataset_name task2 --output_dim 2 --vorder_input "degree_nodecentrality,eigenvec_nodecentrality,pagerank_nodecentrality,kcore_nodecentrality" --embedder whatsnet --att_type_v OrderPE --agg_type_v PrevQ --att_type_e OrderPE --agg_type_e PrevQ --num_att_layer 2 --num_layers 1 --scorer sm --scorer_num_layers 1 --bs 1024 --lr 0.001 --sampling 40 --dropout 0.7 --optimizer "adam" --k 0 --gamma 0.99 --dim_hidden 64 --dim_edge 128 --dim_vertex 128 --epochs 100 --test_epoch 1 --evaltype test --save_epochs 1 --seed 42 --fix_seed --recalculate --use_wandb=1 --run_name='[Task2] DefaultArgs'

# [Task2] AttLayer4
#CUDA_VISIBLE_DEVICES=3 python train.py --dataset_name task2 --output_dim 2 --vorder_input "degree_nodecentrality,eigenvec_nodecentrality,pagerank_nodecentrality,kcore_nodecentrality" --embedder whatsnet --att_type_v OrderPE --agg_type_v PrevQ --att_type_e OrderPE --agg_type_e PrevQ --num_att_layer 4 --num_layers 1 --scorer sm --scorer_num_layers 1 --bs 1024 --lr 0.001 --sampling 40 --dropout 0.7 --optimizer "adam" --k 0 --gamma 0.99 --dim_hidden 64 --dim_edge 128 --dim_vertex 128 --epochs 100 --test_epoch 1 --evaltype test --save_epochs 1 --seed 42 --fix_seed --recalculate --use_wandb=1 --run_name='[Task2] AttLayer4'

# [Task2] ScorerNumLayer2
#CUDA_VISIBLE_DEVICES=2 python train.py --dataset_name task2 --output_dim 2 --vorder_input "degree_nodecentrality,eigenvec_nodecentrality,pagerank_nodecentrality,kcore_nodecentrality" --embedder whatsnet --att_type_v OrderPE --agg_type_v PrevQ --att_type_e OrderPE --agg_type_e PrevQ --num_att_layer 2 --num_layers 1 --scorer sm --scorer_num_layers 2 --bs 1024 --lr 0.001 --sampling 40 --dropout 0.7 --optimizer "adam" --k 0 --gamma 0.99 --dim_hidden 64 --dim_edge 128 --dim_vertex 128 --epochs 100 --test_epoch 1 --evaltype test --save_epochs 1 --seed 42 --fix_seed --recalculate --use_wandb=1 --run_name='[Task2] ScorerNumLayer2'

# [Task2] ScorerNumLayer4
#CUDA_VISIBLE_DEVICES=3 python train.py --dataset_name task2 --output_dim 2 --vorder_input "degree_nodecentrality,eigenvec_nodecentrality,pagerank_nodecentrality,kcore_nodecentrality" --embedder whatsnet --att_type_v OrderPE --agg_type_v PrevQ --att_type_e OrderPE --agg_type_e PrevQ --num_att_layer 2 --num_layers 1 --scorer sm --scorer_num_layers 4 --bs 1024 --lr 0.001 --sampling 40 --dropout 0.7 --optimizer "adam" --k 0 --gamma 0.99 --dim_hidden 64 --dim_edge 128 --dim_vertex 128 --epochs 100 --test_epoch 1 --evaltype test --save_epochs 1 --seed 42 --fix_seed --recalculate --use_wandb=1 --run_name='[Task2] ScorerNumLayer4'



